# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy with maven

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: maven
    - name: Get the version
      id: tag
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Relocate Packages
      run: |
        export VERSION=$(sed 's/[\.-]/_/g' <<<${{ steps.tag.outputs.VERSION }})
        mkdir temp
        mv src/main/java/me/tippie/tippieutils/* temp/
        mkdir src/main/java/me/tippie/tippieutils/$VERSION
        mv temp/* src/main/java/me/tippie/tippieutils/$VERSION/
        find . -type f -exec sed -i 's@me\.tippie\.tippieutils@me\.tippie\.tippieutils\.'"$VERSION"'@g' {} +
    - uses: s4u/maven-settings-action@v2.3.0
      with:
          servers: |
            [{
                "id": "tippie-repo",
                "username": "${{ secrets.TIPPIE_REPO_USERNAME }}",
                "password": "${{ secrets.TIPPIE_REPO_PASSWORD }}"
            }]
    - name: Build with Maven
      run: mvn -B package javadoc:jar source:jar org.apache.maven.plugins:maven-javadoc-plugin:3.3.1:aggregate --file pom.xml
    - name: Deploy to tippie-repo
      run: mvn deploy
    - name: Deploy javadoc
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'javadoc'
        clean: true
        folder: target/site/apidocs
        target-folder: .

